server:
  port: 8086

consumer:
  activemq:
    broker:
      url: tcp://localhost:61616
      max:
        connections: 10
        sessions: 10
  consumer:
    concurrency: 1-5

producer:
  activemq:
    broker:
      url: tcp://localhost:61616
    task:
      processing:
        limit: 30000000

# Replace this with an API key available at
# https://console.developers.google.com/project/_/apiui/credential
youtube:
  apikey: AIzaSyDotKFb0y1kis-82lriyJdS6xCyaAJPDCw